[2025-05-15T16:57:06.480+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T16:57:06.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T16:57:06.486+0000] {logging_mixin.py:190} INFO - [2025-05-15T16:57:06.486+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T16:57:06.608+0000] {logging_mixin.py:190} INFO - [2025-05-15T16:57:06.603+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T16:57:06.609+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T16:57:06.706+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.234 seconds
[2025-05-15T16:57:36.805+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T16:57:36.806+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T16:57:36.808+0000] {logging_mixin.py:190} INFO - [2025-05-15T16:57:36.808+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T16:57:36.855+0000] {logging_mixin.py:190} INFO - [2025-05-15T16:57:36.852+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T16:57:36.856+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T16:57:36.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.121 seconds
[2025-05-15T16:58:07.128+0000] {processor.py:186} INFO - Started process (PID=191) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T16:58:07.128+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T16:58:07.131+0000] {logging_mixin.py:190} INFO - [2025-05-15T16:58:07.130+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T16:58:07.182+0000] {logging_mixin.py:190} INFO - [2025-05-15T16:58:07.177+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T16:58:07.183+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T16:58:07.249+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.127 seconds
[2025-05-15T16:58:38.120+0000] {processor.py:186} INFO - Started process (PID=255) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T16:58:38.121+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T16:58:38.123+0000] {logging_mixin.py:190} INFO - [2025-05-15T16:58:38.123+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T16:58:38.168+0000] {logging_mixin.py:190} INFO - [2025-05-15T16:58:38.165+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T16:58:38.169+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T16:58:38.237+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.122 seconds
[2025-05-15T16:59:08.776+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T16:59:08.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T16:59:08.779+0000] {logging_mixin.py:190} INFO - [2025-05-15T16:59:08.779+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T16:59:08.827+0000] {logging_mixin.py:190} INFO - [2025-05-15T16:59:08.824+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T16:59:08.828+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T16:59:08.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.127 seconds
[2025-05-15T16:59:39.133+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T16:59:39.135+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T16:59:39.141+0000] {logging_mixin.py:190} INFO - [2025-05-15T16:59:39.141+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T16:59:39.208+0000] {logging_mixin.py:190} INFO - [2025-05-15T16:59:39.203+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T16:59:39.209+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T16:59:39.306+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.186 seconds
[2025-05-15T17:00:09.660+0000] {processor.py:186} INFO - Started process (PID=447) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:00:09.661+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:00:09.664+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:00:09.664+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:00:09.713+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:00:09.710+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:00:09.713+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:00:09.779+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.124 seconds
[2025-05-15T17:00:40.239+0000] {processor.py:186} INFO - Started process (PID=511) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:00:40.240+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:00:40.243+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:00:40.242+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:00:40.288+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:00:40.284+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:00:40.288+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:00:40.355+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.122 seconds
[2025-05-15T17:01:10.395+0000] {processor.py:186} INFO - Started process (PID=575) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:01:10.396+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:01:10.399+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:01:10.398+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:01:10.445+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:01:10.442+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:01:10.446+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:01:10.510+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.120 seconds
[2025-05-15T17:01:40.847+0000] {processor.py:186} INFO - Started process (PID=639) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:01:40.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:01:40.853+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:01:40.852+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:01:40.926+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:01:40.922+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:01:40.927+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:01:41.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.177 seconds
[2025-05-15T17:02:11.453+0000] {processor.py:186} INFO - Started process (PID=703) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:02:11.454+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:02:11.457+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:02:11.457+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:02:11.504+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:02:11.501+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:02:11.504+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:02:11.570+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.123 seconds
[2025-05-15T17:02:41.824+0000] {processor.py:186} INFO - Started process (PID=767) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:02:41.825+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:02:41.828+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:02:41.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:02:41.885+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:02:41.881+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:02:41.885+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:02:41.960+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.143 seconds
[2025-05-15T17:05:24.360+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:05:24.361+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:05:24.366+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:05:24.365+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:05:24.418+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:05:24.414+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:05:24.419+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:05:24.500+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.149 seconds
[2025-05-15T17:05:54.896+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:05:54.897+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:05:54.899+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:05:54.899+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:05:54.950+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:05:54.947+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:05:54.951+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:05:55.020+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.130 seconds
[2025-05-15T17:06:25.451+0000] {processor.py:186} INFO - Started process (PID=191) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:06:25.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:06:25.456+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:06:25.456+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:06:25.514+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:06:25.509+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:06:25.515+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:06:25.596+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.153 seconds
[2025-05-15T17:06:55.721+0000] {processor.py:186} INFO - Started process (PID=255) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:06:55.722+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:06:55.725+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:06:55.724+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:06:55.774+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:06:55.771+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:06:55.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:06:55.841+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.126 seconds
[2025-05-15T17:07:26.339+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:07:26.340+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:07:26.343+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:07:26.342+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:07:26.390+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:07:26.387+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:07:26.390+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:07:26.458+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.125 seconds
[2025-05-15T17:07:56.622+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:07:56.623+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:07:56.625+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:07:56.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:07:56.676+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:07:56.672+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:07:56.677+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:07:56.762+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.147 seconds
[2025-05-15T17:08:26.932+0000] {processor.py:186} INFO - Started process (PID=447) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:08:26.933+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:08:26.936+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:08:26.935+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:08:26.984+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:08:26.981+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:08:26.985+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:08:27.052+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.129 seconds
[2025-05-15T17:08:57.275+0000] {processor.py:186} INFO - Started process (PID=511) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:08:57.276+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:08:57.279+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:08:57.279+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:08:57.330+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:08:57.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:08:57.331+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:08:57.401+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.133 seconds
[2025-05-15T17:09:27.504+0000] {processor.py:186} INFO - Started process (PID=575) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:09:27.505+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:09:27.508+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:09:27.508+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:09:27.557+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:09:27.554+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:09:27.557+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:09:27.631+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.132 seconds
[2025-05-15T17:09:57.694+0000] {processor.py:186} INFO - Started process (PID=639) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:09:57.695+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:09:57.699+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:09:57.698+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:09:57.743+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:09:57.739+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:09:57.744+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:09:57.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.127 seconds
[2025-05-15T17:10:28.255+0000] {processor.py:186} INFO - Started process (PID=703) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:10:28.256+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:10:28.258+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:10:28.258+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:10:28.307+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:10:28.304+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:10:28.308+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:10:28.375+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.127 seconds
[2025-05-15T17:10:58.411+0000] {processor.py:186} INFO - Started process (PID=767) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:10:58.412+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:10:58.415+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:10:58.415+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:10:58.462+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:10:58.459+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:10:58.462+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:10:58.533+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.128 seconds
[2025-05-15T17:11:29.543+0000] {processor.py:186} INFO - Started process (PID=831) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:11:29.544+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:11:29.546+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:11:29.546+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:11:29.598+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:11:29.595+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:11:29.599+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:11:29.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.132 seconds
[2025-05-15T17:11:32.106+0000] {processor.py:186} INFO - Started process (PID=850) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:11:32.107+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:11:32.109+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:11:32.109+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:11:32.121+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:11:32.121+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 12
    from extraction.mercadolivre.scriptget_seller_shipping_cost
                                                               ^
SyntaxError: invalid syntax
[2025-05-15T17:11:32.122+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:11:32.186+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.085 seconds
[2025-05-15T17:11:36.230+0000] {processor.py:186} INFO - Started process (PID=851) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:11:36.230+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:11:36.233+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:11:36.233+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:11:36.246+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:11:36.246+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 12
    from extraction.mercadolivre.script.get_seller_shipping_cost import 
                                                                        ^
SyntaxError: invalid syntax
[2025-05-15T17:11:36.247+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:11:36.314+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.090 seconds
[2025-05-15T17:12:07.161+0000] {processor.py:186} INFO - Started process (PID=915) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:12:07.162+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:12:07.164+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:12:07.164+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:12:07.177+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:12:07.176+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 12
    from extraction.mercadolivre.script.get_seller_shipping_cost import 
                                                                        ^
SyntaxError: invalid syntax
[2025-05-15T17:12:07.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:12:07.241+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.084 seconds
[2025-05-15T17:12:15.624+0000] {processor.py:186} INFO - Started process (PID=946) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:12:15.625+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:12:15.627+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:12:15.627+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:12:15.682+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:12:15.678+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:12:15.682+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:12:15.747+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.129 seconds
[2025-05-15T17:12:23.906+0000] {processor.py:186} INFO - Started process (PID=956) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:12:23.907+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:12:23.909+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:12:23.908+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:12:23.965+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:12:23.962+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:12:23.967+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:12:24.041+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.143 seconds
[2025-05-15T17:12:54.965+0000] {processor.py:186} INFO - Started process (PID=1020) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:12:54.966+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:12:54.968+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:12:54.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:12:55.016+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:12:55.013+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:12:55.016+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:12:55.095+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.136 seconds
[2025-05-15T17:13:25.844+0000] {processor.py:186} INFO - Started process (PID=1090) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:13:25.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:13:25.848+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:13:25.847+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:13:25.897+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:13:25.893+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:13:25.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:13:25.965+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.127 seconds
[2025-05-15T17:13:30.960+0000] {processor.py:186} INFO - Started process (PID=1091) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:13:30.961+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:13:30.963+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:13:30.963+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:13:30.978+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:13:30.977+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 11
    from extraction.mercadolivre.scriptextract_data
                                                   ^
SyntaxError: invalid syntax
[2025-05-15T17:13:30.979+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:13:31.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.095 seconds
[2025-05-15T17:13:32.064+0000] {processor.py:186} INFO - Started process (PID=1092) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:13:32.066+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:13:32.070+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:13:32.069+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:13:32.083+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:13:32.082+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 11
    from extraction.mercadolivre.script,extract_data 
                                       ^
SyntaxError: invalid syntax
[2025-05-15T17:13:32.083+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:13:32.155+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.099 seconds
[2025-05-15T17:13:35.648+0000] {processor.py:186} INFO - Started process (PID=1111) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:13:35.649+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:13:35.651+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:13:35.651+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:13:35.664+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:13:35.663+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 11
    from extraction.mercadolivre.script.extract_data 
                                                     ^
SyntaxError: invalid syntax
[2025-05-15T17:13:35.664+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:13:35.732+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.090 seconds
[2025-05-15T17:13:38.693+0000] {processor.py:186} INFO - Started process (PID=1112) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:13:38.694+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:13:38.696+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:13:38.696+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:13:38.709+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:13:38.708+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 11
    from extraction.mercadolivre.script.extract_data import 
                                                            ^
SyntaxError: invalid syntax
[2025-05-15T17:13:38.710+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:13:38.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.091 seconds
[2025-05-15T17:13:54.313+0000] {processor.py:186} INFO - Started process (PID=1152) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:13:54.314+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:13:54.317+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:13:54.317+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:13:54.368+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:13:54.365+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:13:54.369+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:13:54.434+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.127 seconds
[2025-05-15T17:14:00.455+0000] {processor.py:186} INFO - Started process (PID=1159) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:14:00.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:14:00.458+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:00.458+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:14:00.511+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:00.508+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 25, in <module>
    ml_access_token = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-15T17:14:00.512+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:14:00.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.129 seconds
[2025-05-15T17:14:07.311+0000] {processor.py:186} INFO - Started process (PID=1178) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:14:07.313+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:14:07.315+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:07.315+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:14:07.329+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:07.328+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 10
    from extraction.mercadolivre.script.get_access_token
                                                        ^
SyntaxError: invalid syntax
[2025-05-15T17:14:07.330+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:14:07.401+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.097 seconds
[2025-05-15T17:14:15.705+0000] {processor.py:186} INFO - Started process (PID=1183) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:14:15.706+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:14:15.708+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:15.708+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:14:15.722+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:15.721+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 10
    from extraction.mercadolivre.script.get_access_token import 
                                                                ^
SyntaxError: invalid syntax
[2025-05-15T17:14:15.723+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:14:15.796+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.096 seconds
[2025-05-15T17:14:19.887+0000] {processor.py:186} INFO - Started process (PID=1208) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:14:19.888+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:14:19.890+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:19.890+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:14:19.942+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:14:20.098+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:20.098+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:01_extract_data
[2025-05-15T17:14:20.108+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:20.108+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:01_extract_data
[2025-05-15T17:14:20.116+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:20.115+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:01_extract_data
[2025-05-15T17:14:20.124+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:20.124+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:01_extract_data
[2025-05-15T17:14:20.130+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:20.130+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:01_extract_data
[2025-05-15T17:14:20.137+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:20.137+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:01_extract_data
[2025-05-15T17:14:20.144+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:20.143+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:01_extract_data
[2025-05-15T17:14:20.144+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:20.144+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:14:20.161+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:20.161+0000] {dag.py:3262} INFO - Creating ORM DAG for 01_extract_data
[2025-05-15T17:14:20.162+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:20.162+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:14:20.205+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.324 seconds
[2025-05-15T17:14:50.890+0000] {processor.py:186} INFO - Started process (PID=1272) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:14:50.891+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:14:50.893+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:50.893+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:14:50.939+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:14:51.008+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:51.008+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:14:51.029+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:14:51.029+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:14:51.062+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.177 seconds
[2025-05-15T17:15:21.673+0000] {processor.py:186} INFO - Started process (PID=1332) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:15:21.674+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:15:21.676+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:15:21.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:15:21.725+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:15:21.794+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:15:21.793+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:15:21.814+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:15:21.814+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:15:21.837+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.169 seconds
[2025-05-15T17:15:52.132+0000] {processor.py:186} INFO - Started process (PID=1396) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:15:52.134+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:15:52.136+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:15:52.136+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:15:52.187+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:15:52.256+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:15:52.256+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:15:52.275+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:15:52.274+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:15:52.293+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.168 seconds
[2025-05-15T17:16:22.651+0000] {processor.py:186} INFO - Started process (PID=1451) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:16:22.652+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:16:22.654+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:16:22.654+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:16:22.705+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:16:22.770+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:16:22.770+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:16:22.789+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:16:22.789+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:16:22.809+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.164 seconds
[2025-05-15T17:16:54.518+0000] {processor.py:186} INFO - Started process (PID=1515) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:16:54.519+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:16:54.521+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:16:54.521+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:16:54.574+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:16:54.653+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:16:54.653+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:16:54.676+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:16:54.676+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:16:54.702+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.191 seconds
[2025-05-15T17:17:25.481+0000] {processor.py:186} INFO - Started process (PID=1576) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:17:25.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:17:25.484+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:17:25.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:17:25.536+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:17:25.622+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:17:25.622+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:17:25.642+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:17:25.642+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:17:25.668+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.194 seconds
[2025-05-15T17:17:40.994+0000] {processor.py:186} INFO - Started process (PID=1629) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:17:40.994+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:17:40.996+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:17:40.996+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:17:41.009+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:17:41.009+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 17
    ]'01_extract_data',
     ^
SyntaxError: invalid syntax
[2025-05-15T17:17:41.010+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:17:41.067+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.079 seconds
[2025-05-15T17:17:45.068+0000] {processor.py:186} INFO - Started process (PID=1630) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:17:45.069+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:17:45.072+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:17:45.071+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:17:45.124+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:17:45.191+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:17:45.191+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:17:45.210+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:17:45.209+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:17:45.236+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.174 seconds
[2025-05-15T17:17:57.064+0000] {processor.py:186} INFO - Started process (PID=1648) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:17:57.066+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:17:57.069+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:17:57.069+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:17:57.096+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:17:57.092+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 10, in <module>
    from libs.extraction.extraction_pipeline import extract_data
ModuleNotFoundError: No module named 'libs'
[2025-05-15T17:17:57.097+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:17:57.209+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.151 seconds
[2025-05-15T17:18:04.368+0000] {processor.py:186} INFO - Started process (PID=1677) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:18:04.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:18:04.371+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:18:04.371+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:18:04.421+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:18:04.490+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:18:04.490+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:18:04.511+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:18:04.511+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:18:04.539+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.177 seconds
[2025-05-15T17:18:24.880+0000] {processor.py:186} INFO - Started process (PID=1700) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:18:24.881+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:18:24.884+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:18:24.883+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:18:24.935+0000] {processor.py:925} INFO - DAG(s) '01_extracting_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:18:25.073+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:18:25.073+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:01_extracting_data
[2025-05-15T17:18:25.082+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:18:25.082+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:01_extracting_data
[2025-05-15T17:18:25.087+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:18:25.087+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:01_extracting_data
[2025-05-15T17:18:25.095+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:18:25.094+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:01_extracting_data
[2025-05-15T17:18:25.101+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:18:25.101+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:01_extracting_data
[2025-05-15T17:18:25.108+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:18:25.107+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:01_extracting_data
[2025-05-15T17:18:25.114+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:18:25.114+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:01_extracting_data
[2025-05-15T17:18:25.115+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:18:25.114+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:18:25.132+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:18:25.132+0000] {dag.py:3262} INFO - Creating ORM DAG for 01_extracting_data
[2025-05-15T17:18:25.133+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:18:25.133+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extracting_data to None, run_after=None
[2025-05-15T17:18:25.153+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.278 seconds
[2025-05-15T17:18:55.244+0000] {processor.py:186} INFO - Started process (PID=1764) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:18:55.245+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:18:55.248+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:18:55.248+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:18:55.289+0000] {processor.py:925} INFO - DAG(s) '01_extracting_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:18:55.354+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:18:55.354+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:18:55.373+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:18:55.373+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extracting_data to None, run_after=None
[2025-05-15T17:18:55.395+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.158 seconds
[2025-05-15T17:19:03.616+0000] {processor.py:186} INFO - Started process (PID=1806) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:19:03.617+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:19:03.619+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:19:03.619+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:19:03.671+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:19:03.748+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:19:03.748+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:19:03.769+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:19:03.768+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:19:03.793+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.183 seconds
[2025-05-15T17:19:34.736+0000] {processor.py:186} INFO - Started process (PID=1870) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:19:34.737+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:19:34.739+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:19:34.739+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:19:34.786+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:19:34.856+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:19:34.855+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:19:34.877+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:19:34.877+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:19:34.906+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.176 seconds
[2025-05-15T17:20:05.824+0000] {processor.py:186} INFO - Started process (PID=1935) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:20:05.824+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:20:05.826+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:20:05.826+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:20:05.878+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:20:05.947+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:20:05.947+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:20:05.968+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:20:05.967+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:20:05.990+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.172 seconds
[2025-05-15T17:20:06.922+0000] {processor.py:186} INFO - Started process (PID=1936) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:20:06.923+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:20:06.925+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:20:06.925+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:20:06.981+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:20:06.980+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 480, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 499, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 508, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 81, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 67, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: 01_extract_data. Faulty task: ml_access_token
[2025-05-15T17:20:06.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:20:07.065+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.149 seconds
[2025-05-15T17:20:08.047+0000] {processor.py:186} INFO - Started process (PID=1937) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:20:08.048+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:20:08.051+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:20:08.051+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:20:08.114+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:20:08.113+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 480, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 499, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 508, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 81, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 67, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: 01_extract_data. Faulty task: ml_access_token
[2025-05-15T17:20:08.114+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:20:08.186+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.145 seconds
[2025-05-15T17:20:38.388+0000] {processor.py:186} INFO - Started process (PID=2001) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:20:38.389+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:20:38.390+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:20:38.390+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:20:38.438+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:20:38.437+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 480, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 499, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 508, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 81, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 67, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: 01_extract_data. Faulty task: ml_access_token
[2025-05-15T17:20:38.439+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:20:38.510+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.128 seconds
[2025-05-15T17:21:08.796+0000] {processor.py:186} INFO - Started process (PID=2065) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:08.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:21:08.798+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:08.798+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:08.842+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:08.841+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 480, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 499, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 508, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 81, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 67, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: 01_extract_data. Faulty task: ml_access_token
[2025-05-15T17:21:08.843+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:08.909+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.119 seconds
[2025-05-15T17:21:26.314+0000] {processor.py:186} INFO - Started process (PID=2094) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:26.315+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:21:26.316+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:26.316+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:26.367+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:26.364+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 17, in <module>
    start_date=datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2025-05-15T17:21:26.368+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:26.432+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.124 seconds
[2025-05-15T17:21:30.361+0000] {processor.py:186} INFO - Started process (PID=2095) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:30.362+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:21:30.363+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:30.363+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:30.413+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:30.410+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 17, in <module>
    start_date=d/dt.atetime(2023, 1, 1),
NameError: name 'd' is not defined
[2025-05-15T17:21:30.414+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:30.478+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.123 seconds
[2025-05-15T17:21:33.542+0000] {processor.py:186} INFO - Started process (PID=2096) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:33.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:21:33.544+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:33.544+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:33.593+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:33.591+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 17, in <module>
    start_date=dt.atetime(2023, 1, 1),
AttributeError: module 'datetime' has no attribute 'atetime'
[2025-05-15T17:21:33.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:33.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.123 seconds
[2025-05-15T17:21:35.626+0000] {processor.py:186} INFO - Started process (PID=2102) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:35.627+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:21:35.628+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:35.628+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:35.677+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:35.676+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 480, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 499, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 508, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 81, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 67, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: 01_extract_data. Faulty task: ml_access_token
[2025-05-15T17:21:35.678+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:35.744+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.124 seconds
[2025-05-15T17:21:37.759+0000] {processor.py:186} INFO - Started process (PID=2120) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:37.759+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:21:37.761+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:37.760+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:37.773+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:37.772+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 19
    ca
    ^
SyntaxError: invalid syntax
[2025-05-15T17:21:37.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:37.845+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.093 seconds
[2025-05-15T17:21:39.042+0000] {processor.py:186} INFO - Started process (PID=2131) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:39.043+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:21:39.044+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:39.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:39.060+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:39.059+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 19
    cat
    ^
SyntaxError: invalid syntax
[2025-05-15T17:21:39.060+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:39.137+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.101 seconds
[2025-05-15T17:21:42.792+0000] {processor.py:186} INFO - Started process (PID=2141) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:42.793+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:21:42.795+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:42.795+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:42.810+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:42.809+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 19
    catchup=Fal
    ^
SyntaxError: invalid syntax
[2025-05-15T17:21:42.810+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:42.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.094 seconds
[2025-05-15T17:21:44.419+0000] {processor.py:186} INFO - Started process (PID=2149) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:44.420+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:21:44.422+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:44.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:44.434+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:44.433+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/01_extract_data.py", line 19
    catchup=False
    ^
SyntaxError: invalid syntax
[2025-05-15T17:21:44.435+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:44.516+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.103 seconds
[2025-05-15T17:21:45.934+0000] {processor.py:186} INFO - Started process (PID=2155) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:45.935+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:21:45.936+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:45.936+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:45.994+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:21:45.993+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 480, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 499, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 508, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 81, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 67, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: 01_extract_data. Faulty task: ml_access_token
[2025-05-15T17:21:45.995+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:21:46.070+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.143 seconds
[2025-05-15T17:22:16.398+0000] {processor.py:186} INFO - Started process (PID=2219) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:22:16.399+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:22:16.400+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:22:16.400+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:22:16.448+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:22:16.447+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 480, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 499, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 508, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 81, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 67, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: 01_extract_data. Faulty task: ml_access_token
[2025-05-15T17:22:16.449+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:22:16.521+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.129 seconds
[2025-05-15T17:22:46.682+0000] {processor.py:186} INFO - Started process (PID=2283) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:22:46.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:22:46.686+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:22:46.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:22:46.739+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:22:46.738+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 480, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 499, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 508, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 81, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 67, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: 01_extract_data. Faulty task: ml_access_token
[2025-05-15T17:22:46.739+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:22:46.810+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.136 seconds
[2025-05-15T17:23:16.907+0000] {processor.py:186} INFO - Started process (PID=2347) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:23:16.908+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:23:16.910+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:23:16.909+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:23:16.955+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:23:16.955+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 480, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 499, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 508, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 81, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 67, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: 01_extract_data. Faulty task: ml_access_token
[2025-05-15T17:23:16.956+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:23:17.021+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.120 seconds
[2025-05-15T17:23:47.204+0000] {processor.py:186} INFO - Started process (PID=2411) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:23:47.205+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:23:47.206+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:23:47.206+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:23:47.255+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:23:47.255+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/01_extract_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 480, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 499, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 508, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 81, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/dag_cycle_tester.py", line 67, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: 01_extract_data. Faulty task: ml_access_token
[2025-05-15T17:23:47.256+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:23:47.344+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.146 seconds
[2025-05-15T17:24:12.279+0000] {processor.py:186} INFO - Started process (PID=2429) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:24:12.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:24:12.281+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:24:12.281+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:24:12.336+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:24:12.489+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:24:12.489+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:24:12.508+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:24:12.508+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:24:12.540+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.267 seconds
[2025-05-15T17:24:43.554+0000] {processor.py:186} INFO - Started process (PID=2492) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:24:43.555+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:24:43.556+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:24:43.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:24:43.611+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:24:43.691+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:24:43.691+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:24:43.713+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:24:43.713+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:24:43.737+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.190 seconds
[2025-05-15T17:25:14.452+0000] {processor.py:186} INFO - Started process (PID=2555) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:25:14.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:25:14.455+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:25:14.454+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:25:14.507+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:25:14.578+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:25:14.577+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:25:14.599+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:25:14.599+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:25:14.624+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.177 seconds
[2025-05-15T17:25:38.775+0000] {processor.py:186} INFO - Started process (PID=2614) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:25:38.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:25:38.777+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:25:38.777+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:25:38.832+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:25:38.902+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:25:38.902+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:25:38.922+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:25:38.921+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:25:38.945+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.176 seconds
[2025-05-15T17:25:42.858+0000] {processor.py:186} INFO - Started process (PID=2615) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:25:42.859+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:25:42.860+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:25:42.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:25:42.912+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:25:42.981+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:25:42.981+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:25:43.001+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:25:43.001+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:25:43.027+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.175 seconds
[2025-05-15T17:25:45.052+0000] {processor.py:186} INFO - Started process (PID=2616) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:25:45.053+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:25:45.054+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:25:45.054+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:25:45.107+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:25:45.174+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:25:45.174+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:25:45.196+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:25:45.195+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:25:45.222+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.177 seconds
[2025-05-15T17:25:47.295+0000] {processor.py:186} INFO - Started process (PID=2631) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:25:47.297+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:25:47.299+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:25:47.298+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:25:47.370+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:25:47.489+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:25:47.488+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:25:47.517+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:25:47.517+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:25:47.554+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.268 seconds
[2025-05-15T17:26:18.592+0000] {processor.py:186} INFO - Started process (PID=2695) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:26:18.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:26:18.594+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:26:18.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:26:18.646+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:26:18.723+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:26:18.723+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:26:18.745+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:26:18.745+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:26:18.764+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.178 seconds
[2025-05-15T17:26:48.806+0000] {processor.py:186} INFO - Started process (PID=2758) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:26:48.807+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:26:48.808+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:26:48.808+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:26:48.857+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:26:48.953+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:26:48.953+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:26:48.977+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:26:48.977+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:26:48.999+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.199 seconds
[2025-05-15T17:27:19.140+0000] {processor.py:186} INFO - Started process (PID=2821) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:27:19.141+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:27:19.142+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:27:19.142+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:27:19.187+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:27:19.256+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:27:19.256+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:27:19.277+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:27:19.277+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:27:19.298+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.163 seconds
[2025-05-15T17:27:49.764+0000] {processor.py:186} INFO - Started process (PID=2883) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:27:49.765+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:27:49.766+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:27:49.766+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:27:49.815+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:27:49.879+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:27:49.879+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:27:49.898+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:27:49.898+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:27:49.917+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.159 seconds
[2025-05-15T17:28:20.099+0000] {processor.py:186} INFO - Started process (PID=2944) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:28:20.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:28:20.101+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:28:20.101+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:28:20.158+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:28:20.243+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:28:20.243+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:28:20.268+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:28:20.268+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:28:20.296+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.204 seconds
[2025-05-15T17:28:50.967+0000] {processor.py:186} INFO - Started process (PID=3008) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:28:50.968+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:28:50.970+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:28:50.969+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:28:51.025+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:28:51.101+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:28:51.100+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:28:51.124+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:28:51.124+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:28:51.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.190 seconds
[2025-05-15T17:29:21.376+0000] {processor.py:186} INFO - Started process (PID=3071) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:29:21.377+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:29:21.378+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:29:21.378+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:29:21.458+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:29:21.586+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:29:21.586+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:29:21.615+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:29:21.615+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:29:21.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.275 seconds
[2025-05-15T17:29:51.862+0000] {processor.py:186} INFO - Started process (PID=3135) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:29:51.863+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:29:51.864+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:29:51.864+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:29:51.915+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:29:51.987+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:29:51.987+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:29:52.008+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:29:52.008+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:29:52.031+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.177 seconds
[2025-05-15T17:30:22.857+0000] {processor.py:186} INFO - Started process (PID=3199) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:30:22.858+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:30:22.859+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:30:22.859+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:30:22.907+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:30:22.974+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:30:22.974+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:30:22.995+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:30:22.994+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:30:23.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.163 seconds
[2025-05-15T17:30:53.291+0000] {processor.py:186} INFO - Started process (PID=3264) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:30:53.292+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:30:53.293+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:30:53.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:30:53.342+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:30:53.409+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:30:53.409+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:30:53.430+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:30:53.430+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:30:53.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.168 seconds
[2025-05-15T17:31:53.435+0000] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:31:53.436+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:31:53.440+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:31:53.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:31:53.514+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:31:53.588+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:31:53.588+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:31:53.611+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:31:53.611+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:31:53.635+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.208 seconds
[2025-05-15T17:32:24.403+0000] {processor.py:186} INFO - Started process (PID=130) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:32:24.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:32:24.406+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:32:24.406+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:32:24.464+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:32:24.534+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:32:24.533+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:32:24.555+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:32:24.555+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:32:24.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.178 seconds
[2025-05-15T17:32:54.864+0000] {processor.py:186} INFO - Started process (PID=195) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:32:54.865+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:32:54.867+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:32:54.867+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:32:54.925+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:32:54.993+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:32:54.992+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:32:55.013+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:32:55.013+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:32:55.033+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.175 seconds
[2025-05-15T17:33:25.187+0000] {processor.py:186} INFO - Started process (PID=260) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:33:25.188+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:33:25.191+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:33:25.191+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:33:25.248+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:33:25.311+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:33:25.310+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:33:25.331+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:33:25.331+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:33:25.351+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.172 seconds
[2025-05-15T17:33:56.319+0000] {processor.py:186} INFO - Started process (PID=325) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:33:56.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:33:56.322+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:33:56.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:33:56.376+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:33:56.453+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:33:56.453+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:33:56.477+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:33:56.476+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:33:56.500+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.186 seconds
[2025-05-15T17:34:27.364+0000] {processor.py:186} INFO - Started process (PID=390) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:34:27.365+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:34:27.367+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:34:27.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:34:27.425+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:34:27.494+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:34:27.494+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:34:27.516+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:34:27.516+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:34:27.543+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.185 seconds
[2025-05-15T17:34:57.901+0000] {processor.py:186} INFO - Started process (PID=455) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:34:57.902+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:34:57.904+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:34:57.904+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:34:57.974+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:34:58.049+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:34:58.049+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:34:58.071+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:34:58.071+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:34:58.093+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.199 seconds
[2025-05-15T17:35:28.701+0000] {processor.py:186} INFO - Started process (PID=520) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:35:28.701+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:35:28.704+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:35:28.703+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:35:28.763+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:35:28.839+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:35:28.839+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:35:28.861+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:35:28.861+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:35:28.887+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.193 seconds
[2025-05-15T17:35:59.338+0000] {processor.py:186} INFO - Started process (PID=585) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:35:59.339+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:35:59.341+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:35:59.341+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:35:59.403+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:35:59.481+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:35:59.481+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:35:59.505+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:35:59.505+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:35:59.531+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.200 seconds
[2025-05-15T17:36:29.723+0000] {processor.py:186} INFO - Started process (PID=650) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:36:29.723+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:36:29.726+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:36:29.725+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:36:29.782+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:36:29.849+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:36:29.848+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:36:29.875+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:36:29.875+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:36:29.896+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.179 seconds
[2025-05-15T17:37:00.065+0000] {processor.py:186} INFO - Started process (PID=715) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:37:00.066+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:37:00.068+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:37:00.068+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:37:00.129+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:37:00.206+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:37:00.206+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:37:00.227+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:37:00.227+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:37:00.250+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.190 seconds
[2025-05-15T17:37:30.470+0000] {processor.py:186} INFO - Started process (PID=781) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:37:30.472+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:37:30.479+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:37:30.478+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:37:30.563+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:37:30.643+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:37:30.642+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:37:30.664+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:37:30.663+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:37:30.685+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.226 seconds
[2025-05-15T17:38:01.135+0000] {processor.py:186} INFO - Started process (PID=845) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:38:01.136+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:38:01.139+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:38:01.138+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:38:01.196+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:38:01.269+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:38:01.269+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:38:01.290+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:38:01.290+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:38:01.314+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.184 seconds
[2025-05-15T17:38:31.615+0000] {processor.py:186} INFO - Started process (PID=910) to work on /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:38:31.616+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/01_extract_data.py for tasks to queue
[2025-05-15T17:38:31.619+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:38:31.618+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:38:31.681+0000] {processor.py:925} INFO - DAG(s) '01_extract_data' retrieved from /opt/airflow/dags/01_extract_data.py
[2025-05-15T17:38:31.781+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:38:31.780+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-15T17:38:31.819+0000] {logging_mixin.py:190} INFO - [2025-05-15T17:38:31.819+0000] {dag.py:4180} INFO - Setting next_dagrun for 01_extract_data to None, run_after=None
[2025-05-15T17:38:31.859+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/01_extract_data.py took 0.250 seconds
