[2025-06-06T19:54:43.448+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-06T19:54:43.472+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 05_transform_data.run_dbt manual__2025-06-06T19:54:34.325152+00:00 [queued]>
[2025-06-06T19:54:43.482+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 05_transform_data.run_dbt manual__2025-06-06T19:54:34.325152+00:00 [queued]>
[2025-06-06T19:54:43.485+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-06-06T19:54:43.500+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_dbt> on 2025-06-06 19:54:34.325152+00:00
[2025-06-06T19:54:43.505+0000] {standard_task_runner.py:72} INFO - Started process 3915 to run task
[2025-06-06T19:54:43.508+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '05_transform_data', 'run_dbt', 'manual__2025-06-06T19:54:34.325152+00:00', '--job-id', '410', '--raw', '--subdir', 'DAGS_FOLDER/05_transform_data.py', '--cfg-path', '/tmp/tmp6f07jnl2']
[2025-06-06T19:54:43.510+0000] {standard_task_runner.py:105} INFO - Job 410: Subtask run_dbt
[2025-06-06T19:54:43.563+0000] {task_command.py:467} INFO - Running <TaskInstance: 05_transform_data.run_dbt manual__2025-06-06T19:54:34.325152+00:00 [running]> on host 28e6a58e4107
[2025-06-06T19:54:43.645+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='05_transform_data' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-06-06T19:54:34.325152+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-06T19:54:34.325152+00:00'
[2025-06-06T19:54:43.647+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-06T19:54:45.541+0000] {logging_mixin.py:190} INFO - 19:54:45  Running with dbt=1.9.5
[2025-06-06T19:54:45.926+0000] {logging_mixin.py:190} INFO - 19:54:45  Registered adapter: postgres=1.9.0
[2025-06-06T19:54:47.930+0000] {logging_mixin.py:190} INFO - 19:54:47  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.e_commerce_sales.example
[2025-06-06T19:54:48.148+0000] {logging_mixin.py:190} INFO - 19:54:48  Found 15 models, 12 sources, 549 macros, 1 unit test
[2025-06-06T19:54:48.153+0000] {logging_mixin.py:190} INFO - 19:54:48
[2025-06-06T19:54:48.155+0000] {logging_mixin.py:190} INFO - 19:54:48  Concurrency: 4 threads (target='dev')
[2025-06-06T19:54:48.157+0000] {logging_mixin.py:190} INFO - 19:54:48
[2025-06-06T19:54:48.296+0000] {logging_mixin.py:190} INFO - 19:54:48  1 of 15 START sql incremental model sales.mercadolivre_orders_results .......... [RUN]
[2025-06-06T19:54:48.299+0000] {logging_mixin.py:190} INFO - 19:54:48  2 of 15 START sql incremental model sales.stg_shopee ........................... [RUN]
[2025-06-06T19:54:48.512+0000] {logging_mixin.py:190} INFO - 19:54:48  2 of 15 ERROR creating sql incremental model sales.stg_shopee .................. [ERROR in 0.21s]
[2025-06-06T19:54:48.520+0000] {logging_mixin.py:190} INFO - 19:54:48  3 of 15 SKIP relation sales.shopee_new_id ...................................... [SKIP]
[2025-06-06T19:54:48.524+0000] {logging_mixin.py:190} INFO - 19:54:48  4 of 15 SKIP relation sales.shopee_orders_results .............................. [SKIP]
[2025-06-06T19:54:48.530+0000] {logging_mixin.py:190} INFO - 19:54:48  5 of 15 SKIP relation sales.dim_shopee_buyer ................................... [SKIP]
[2025-06-06T19:54:48.533+0000] {logging_mixin.py:190} INFO - 19:54:48  6 of 15 SKIP relation sales.dim_shopee_date .................................... [SKIP]
[2025-06-06T19:54:48.534+0000] {logging_mixin.py:190} INFO - 19:54:48  7 of 15 SKIP relation sales.dim_shopee_orders_status ........................... [SKIP]
[2025-06-06T19:54:48.543+0000] {logging_mixin.py:190} INFO - 19:54:48  8 of 15 SKIP relation sales.dim_shopee_product ................................. [SKIP]
[2025-06-06T19:54:48.546+0000] {logging_mixin.py:190} INFO - 19:54:48  9 of 15 SKIP relation sales.sum_shopee_monthly_profit .......................... [SKIP]
[2025-06-06T19:54:48.571+0000] {logging_mixin.py:190} INFO - 19:54:48  10 of 15 SKIP relation sales.sum_shopee_monthly_revenue ........................ [SKIP]
[2025-06-06T19:54:48.580+0000] {logging_mixin.py:190} INFO - 19:54:48  11 of 15 SKIP relation sales.sum_shopee_products_sold .......................... [SKIP]
[2025-06-06T19:54:48.703+0000] {logging_mixin.py:190} INFO - 19:54:48  1 of 15 OK created sql incremental model sales.mercadolivre_orders_results ..... [MERGE 190 in 0.40s]
[2025-06-06T19:54:48.710+0000] {logging_mixin.py:190} INFO - 19:54:48  12 of 15 START sql incremental model sales.dim_mercadolivre_buyer .............. [RUN]
[2025-06-06T19:54:48.712+0000] {logging_mixin.py:190} INFO - 19:54:48  13 of 15 START sql incremental model sales.dim_mercadolivre_date ............... [RUN]
[2025-06-06T19:54:48.713+0000] {logging_mixin.py:190} INFO - 19:54:48  14 of 15 START sql incremental model sales.dim_mercadolivre_orders_status ...... [RUN]
[2025-06-06T19:54:48.715+0000] {logging_mixin.py:190} INFO - 19:54:48  15 of 15 START sql incremental model sales.dim_mercadolivre_product ............ [RUN]
[2025-06-06T19:54:48.949+0000] {logging_mixin.py:190} INFO - 19:54:48  14 of 15 OK created sql incremental model sales.dim_mercadolivre_orders_status . [MERGE 190 in 0.22s]
[2025-06-06T19:54:48.952+0000] {logging_mixin.py:190} INFO - 19:54:48  12 of 15 OK created sql incremental model sales.dim_mercadolivre_buyer ......... [MERGE 188 in 0.23s]
[2025-06-06T19:54:49.036+0000] {logging_mixin.py:190} INFO - 19:54:49  15 of 15 OK created sql incremental model sales.dim_mercadolivre_product ....... [MERGE 65 in 0.31s]
[2025-06-06T19:54:49.050+0000] {logging_mixin.py:190} INFO - 19:54:49  13 of 15 OK created sql incremental model sales.dim_mercadolivre_date .......... [MERGE 190 in 0.33s]
[2025-06-06T19:54:49.074+0000] {logging_mixin.py:190} INFO - 19:54:49
[2025-06-06T19:54:49.076+0000] {logging_mixin.py:190} INFO - 19:54:49  Finished running 12 incremental models, 3 view models in 0 hours 0 minutes and 0.92 seconds (0.92s).
[2025-06-06T19:54:49.154+0000] {logging_mixin.py:190} INFO - 19:54:49
[2025-06-06T19:54:49.155+0000] {logging_mixin.py:190} INFO - 19:54:49  Completed with 1 error, 0 partial successes, and 0 warnings:
[2025-06-06T19:54:49.157+0000] {logging_mixin.py:190} INFO - 19:54:49
[2025-06-06T19:54:49.159+0000] {logging_mixin.py:190} INFO - 19:54:49    Database Error in model stg_shopee (models/staging/stg_shopee.sql)
  syntax error at or near "id_do_pedido"
  LINE 17:         id_do_pedido,
                   ^
  compiled code at target/run/e_commerce_sales/models/staging/stg_shopee.sql
[2025-06-06T19:54:49.160+0000] {logging_mixin.py:190} INFO - 19:54:49
[2025-06-06T19:54:49.162+0000] {logging_mixin.py:190} INFO - 19:54:49  Done. PASS=5 WARN=0 ERROR=1 SKIP=9 TOTAL=15
[2025-06-06T19:54:50.039+0000] {logging_mixin.py:190} INFO - dbt run failed!
[2025-06-06T19:54:50.043+0000] {logging_mixin.py:190} INFO - None
[2025-06-06T19:54:50.045+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dbt_files/run_dbt.py", line 22, in transform_data
    raise RuntimeError("dbt run failed")
RuntimeError: dbt run failed
[2025-06-06T19:54:50.058+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=05_transform_data, task_id=run_dbt, run_id=manual__2025-06-06T19:54:34.325152+00:00, execution_date=20250606T195434, start_date=20250606T195443, end_date=20250606T195450
[2025-06-06T19:54:50.073+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-06T19:54:50.074+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 410 for task run_dbt (dbt run failed; 3915)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dbt_files/run_dbt.py", line 22, in transform_data
    raise RuntimeError("dbt run failed")
RuntimeError: dbt run failed
[2025-06-06T19:54:50.109+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-06T19:54:50.127+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-06T19:54:50.132+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
